"""
ngo_features/donor_report.py — Areapulse-7 integrated
Donor Report PDF generator (branded, with overhead/program split).
Uses portal auth (require_ngo, current_user) and /ngo/api/ convention.
Writes PDF to static/reports/ and returns its URL.
"""

import os
import time
import uuid
from flask import Blueprint, request, jsonify

from auth import require_ngo, current_user

donor_report_bp = Blueprint("donor_report", __name__)

REPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "static", "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)


@donor_report_bp.route("/ngo/api/donor-report", methods=["POST"])
@require_ngo
def generate_report():
    u        = current_user()
    body     = request.get_json(silent=True) or {}
    story    = body.get("story", "")
    stats    = body.get("stats", {}) or {}
    adoptions= body.get("adoptions", []) or []
    budget   = body.get("budget", {}) or {}
    org      = u.get("name", "NGO")

    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle)
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    except Exception as e:
        return jsonify({"error": f"reportlab not available: {e}"}), 500

    FOREST = colors.HexColor("#2D6A4F")
    RUST   = colors.HexColor("#B85042")
    GREY   = colors.HexColor("#6B7280")
    SAND   = colors.HexColor("#F0EBE3")

    fname = f"donor_report_{uuid.uuid4().hex[:8]}.pdf"
    fpath = os.path.join(REPORTS_DIR, fname)
    doc = SimpleDocTemplate(fpath, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm,
                            leftMargin=2*cm, rightMargin=2*cm)
    styles = getSampleStyleSheet()
    h_title = ParagraphStyle("t", parent=styles["Title"], textColor=RUST, fontSize=24, spaceAfter=4)
    h_sub   = ParagraphStyle("s", parent=styles["Normal"], textColor=GREY, fontSize=11, spaceAfter=18)
    h_sec   = ParagraphStyle("sec", parent=styles["Heading2"], textColor=FOREST, fontSize=14, spaceBefore=14, spaceAfter=6)
    body_st = ParagraphStyle("b", parent=styles["Normal"], fontSize=10.5, leading=15, spaceAfter=6)
    story_st= ParagraphStyle("story", parent=styles["Normal"], fontSize=11, leading=17,
                             textColor=FOREST, backColor=SAND, borderPadding=10, spaceAfter=10)

    S = [Paragraph(org, h_title), Paragraph("Donor Impact Report  ·  Generated by AreaPulse", h_sub),
         Paragraph("Impact at a Glance", h_sec)]
    metric_rows = [
        ["Issues Adopted", str(stats.get("total_adopted", 0))],
        ["Issues Resolved", str(stats.get("resolved", 0))],
        ["Volunteers Mobilised", str(stats.get("total_volunteers", 0))],
        ["Residents Impacted", f"{stats.get('residents_impacted', 0):,}"],
        ["Volunteer Drives", str(stats.get("total_drives", 0))],
        ["Government Escalations", str(stats.get("escalations_sent", 0))],
    ]
    t = Table(metric_rows, colWidths=[9*cm, 7*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (0,-1), SAND), ("TEXTCOLOR", (1,0), (1,-1), RUST),
        ("FONTNAME", (1,0), (1,-1), "Helvetica-Bold"), ("FONTSIZE", (0,0), (-1,-1), 11),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8), ("TOPPADDING", (0,0), (-1,-1), 8),
        ("GRID", (0,0), (-1,-1), 0.5, colors.white)]))
    S += [t, Spacer(1, 12)]

    if story and not story.startswith("Click"):
        S += [Paragraph("Impact Story", h_sec), Paragraph(story, story_st)]

    program  = float(budget.get("program", 0) or 0)
    overhead = float(budget.get("overhead", 0) or 0)
    total    = program + overhead
    if total > 0:
        S.append(Paragraph("Fund Utilisation", h_sec))
        brows = [["Category", "Amount (Rs)", "Share"],
                 ["Direct Program Cost", f"{program:,.0f}", f"{round(program/total*100)}%"],
                 ["Operational Overhead", f"{overhead:,.0f}", f"{round(overhead/total*100)}%"],
                 ["Total", f"{total:,.0f}", "100%"]]
        bt = Table(brows, colWidths=[8*cm, 5*cm, 3*cm])
        bt.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), FOREST), ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"), ("FONTNAME", (0,-1), (-1,-1), "Helvetica-Bold"),
            ("FONTSIZE", (0,0), (-1,-1), 10), ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#DDDDDD")),
            ("TOPPADDING", (0,0), (-1,-1), 6), ("BOTTOMPADDING", (0,0), (-1,-1), 6)]))
        S += [bt, Spacer(1, 6), Paragraph(
            "<i>Operational overhead covers coordination, monitoring, compliance, and staff "
            "who make program delivery possible.</i>",
            ParagraphStyle("note", parent=body_st, textColor=GREY, fontSize=9.5))]

    if adoptions:
        S.append(Paragraph("Adopted Issues — Evidence Log", h_sec))
        ev = [["Area", "Type", "Status", "Updates"]]
        for a in adoptions[:15]:
            adopt = a.get("adoption", {}) or {}
            ev.append([str(a.get("area", "")), str(a.get("tag", "")),
                       str(adopt.get("status", "")).replace("_", " "),
                       str(len(adopt.get("updates", [])))])
        et = Table(ev, colWidths=[5*cm, 4*cm, 4*cm, 3*cm])
        et.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), FOREST), ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"), ("FONTSIZE", (0,0), (-1,-1), 9.5),
            ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#DDDDDD")),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, SAND]),
            ("TOPPADDING", (0,0), (-1,-1), 5), ("BOTTOMPADDING", (0,0), (-1,-1), 5)]))
        S.append(et)

    S += [Spacer(1, 20), Paragraph(
        f"Generated {time.strftime('%d %B %Y, %H:%M')} · AreaPulse Civic Platform",
        ParagraphStyle("foot", parent=body_st, textColor=GREY, fontSize=8.5))]

    doc.build(S)
    return jsonify({"status": "ok", "url": f"/static/reports/{fname}", "filename": fname})
